### ISSUE TITLE
Define Design Brief

### ISSUE THREAD

**Issue by arthurrowland** [mcqn/totaliser#1]
It's a Totaliser!

Inspired by Blue Peter's classic fundraising campaign totems which lit up as they jumped closer to the target.

MCQN were bouncing around applications for the The My Baby's Got LED board and this is the one that stuck.

The initial use case is for a crowdfunding campaign HQ - for the team to keep track of the campaign through a fun, physical, bright object for them to be proud of and share online as the pledges come rolling in.

So what's the brief?

- Prototype an engaging totaliser based on the My Baby's Got LED board.

That will do for now. It's going to be, like, totally cool.

**Comment by arthurrowland** [comment]
@amcewen Any expansions on this before closing?

**Comment by amcewen** [comment]
@arthurrowland I don't think so.  The detail is all captured in #2.  :+1:
